pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - https://github.com/BlueMoon817/react-study/weather-app/build
  only:
  - main
