name: Build and Deploy Projects

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: ['rockpaperscissor_game', 'shopping-site', 'weather-app']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: cd ${{ matrix.project }} && npm install

    - name: Build
      run: cd ${{ matrix.project }} && npm run build

    - name: Deploy to GitHub Pages
      run: |
        cd ${{ matrix.project }} && git checkout main || git checkout -b main
        cp -r build/* .
        git add .
        git commit -m "Deploy ${matrix.project}"
        git push origin main