name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    
    # Build and deploy rockpaperscissor_game
    - name: Setup and build in rockpaperscissor_game directory
      run: |
          cd rockpaperscissor_game
          npm install
          npm run build
    - name: Deploy rockpaperscissor_game to GitHub Pages
      run: |
        git checkout main
        cp -r rockpaperscissor_game/build/* ./rockpaperscissor_game/build
        git add ./rockpaperscissor_game/build
        git commit -m "Deploy rockpaperscissor_game/build"
        git push origin main

    # Build and deploy shopping-site
    - name: Setup and build in shopping-site directory
      run: |
        cd shopping-site
        npm install
        npm run build
    - name: Deploy shopping-site to GitHub Pages
      run: |
        git checkout main
        cp -r shopping-site/build/* ./shopping-site/build
        git add ./shopping-site/build
        git commit -m "Deploy shopping-site"
        git push origin main

    - name: Setup and build in weather-app directory
      run: |
        cd weather-app
        npm install
        npm run build
    # Build and deploy weather-app
    - name: Deploy weather-app to GitHub Pages
      run: |
        git checkout main
        cp -r weather-app/build/* ./weather-app/build
        git add ./weather-app/build
        git commit -m "Deploy weather-app"
        git push origin main

