name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout develop branch
      uses: actions/checkout@v2

  - name: Setup and build in rockpaperscissor_game directory
    run: |
      cd rockpaperscissor_game
      npm install
      npm run build

- name: Setup and build in shopping-site directory
  run: |
    cd shopping-site
    npm install
    npm run build

- name: Setup and build in weather-app directory
  run: |
    cd weather-app
    npm install
    npm run build